CUDA_VISIBLE_DEVICES=0 python train.py \
    --config ../rave/configs/v2.gin \
    --db_path /home/buffett/dataset/rave/beatport_data_pp/4secs/ \
    --out_path /home/buffett/dataset/rave/train_configs/ \
    --name beatport_rave \
    --channels 1 \
    --save_every 10000 \
    --batch 16 \
    --workers 24 \
    --sr 44100 \
    --devices 1 \
    --strategy single_device