python train_single_gpu.py \
    --config ../rave/configs/v2_small_no_adversarial.gin \
    --db_path /mnt/gestalt/home/buffett/RAVE/musicnet_data_pp/ \
    --out_path /mnt/gestalt/home/buffett/RAVE/rave_train_configs/ \
    --name musicnet_rave \
    --channels 1 \
    --save_every 10000 \
    --batch 16 \
    --workers 16 \
    --sr 44100 \
    --gpu 3
