# Training Configuration
batch_size: 64
num_workers: 16

# Data loading optimizations
prefetch_factor: 4  # Number of batches to prefetch per worker
cache_size: 1000    # Number of audio files to cache in memory
use_memory_mapping: true  # Use memory mapping for large files
drop_last_train: true     # Drop incomplete batches during training

# Paths
data_dir: "/home/buffett/dataset/rendered_adsr_unpaired"

# Wandb
wandb_use: true
wandb_dir: "/home/buffett/dataset/adsr_reg_logs"
wandb_project: "adsr-reg"
wandb_name: "adsr_623"

# Model
d_model: 1024
d_out: 4  # A,D,S,R
n_heads: 8
n_layers: 16
patch_size: 16
patch_stride: 10
input_channels: 1
spec_shape: [128, 256]

# Optimizer
lr: 1.0e-4
epochs: 400
save_interval: 20


# FFT parameters
sr: 44100
n_fft: 2048
win_length: 2048
hop_length: 512
n_mels: 128
fmin: 20
fmax: 22050
mel_mean: -12.619391
mel_std: 5.2448645

# Lightning specific settings
accelerator: "gpu"
devices: [3]  # Use GPU device 3 specifically
precision: "16-mixed"  # Fixed precision setting
gradient_clip_val: 1.0
accumulate_grad_batches: 1
log_every_n_steps: 50
