# Unit duration in seconds for one audio segment.
# path: /home/buffett/dataset
path: /mnt/gestalt/home/buffett
postfix: "0621"
metadata_dir: ${path}/rendered_adsr_dataset_npy
data_dir: ${path}/rendered_adsr_dataset_npy_new_mel
checkpoint_folder: ${path}/adsr_ckpt
save_dir: ${path}/adsr_training_configs
h5_path: ${path}/adsr_h5/adsr_new_mel.h5

bs: 256 # 256
n_stats: 1000 # 10000
env_amount: 600
pair_amount: 1547

# Wandb parameters.
log_wandb: False #True
wandb_name: byol-a_jun_19_w_h5
device_id: [0]

# FFT parameters.
sample_rate: 44100
n_fft: 2048
win_length: 2048
hop_length: 512
n_mels: 128
f_min: 20
f_max: 22050
# Dimensions of feature representations.
feature_d: 3072
# BYOL parameters.
proj_size: 256
proj_dim: 4096
ema_decay: 0.99
# Training parameters.
seed: 42
num_workers: 24
prefetch_factor: 8

unit_sec: 2.97
lr: 0.0001
epochs: 2 # 100

# Weight pathname for resuming training.
resume:

# Shape of log-mel spectrogram [F, T].
shape: [128, 256] #[64, 96]
